name: Pull Request

on: [pull_request]

jobs:
  build:
    name: Run Tests
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Test with dotnet
        run: dotnet test --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
  pr-check-size:
    name: PR Size
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      issues: write
    steps:
        # - name: Checkout code
        #   uses: actions/checkout@v3
        #   with:
        #     fetch-depth: 0
        # - name: PR Metrics
        #   uses: microsoft/PR-Metrics@v1.6.3
        #   env:
        #     PR_METRICS_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   with:
        #     file-matching-patterns: |
        #       **/*
        #   continue-on-error: true
        - uses: codelytv/pr-size-labeler@v1
          with:
            xs_label: 'size/xs'
            xs_max_size: '10'
            s_label: 'size/s'
            s_max_size: '100'
            m_label: 'size/m'
            m_max_size: '500'
            l_label: 'size/l'
            l_max_size: '1000'
            xl_label: 'size/xl'
            fail_if_xl: 'false'
            message_if_xl: >
              This PR exceeds the recommended size of 1000 lines.
              Please make sure you are NOT addressing multiple issues with one PR.
              Note this PR might be rejected due to its size.
            github_api_url: 'https://api.github.com'
            files_to_ignore: ''
